# 配置数据库的连接字符串
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java_chatroom?characterEncoding=utf8&useSSl=false
    username: root
    password: dy2lwy
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    port: 25
    username: wetalk2023@163.com
    password: KCQEIMYUXTYIQKGN
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: 43.139.243.98
    port: 6379


mybatis:
  mapper-locations: classpath:/mybatis/*Mapper.xml


